// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ZqZEUi9F0_J_2y4ZM1Bfo4LqC3CPb6Y',
    appId: '1:556603482761:web:b3054d23edd6b9d6875c58',
    messagingSenderId: '556603482761',
    projectId: 'ambulance-a27af',
    authDomain: 'ambulance-a27af.firebaseapp.com',
    storageBucket: 'ambulance-a27af.appspot.com',
    measurementId: 'G-FCQP6L7YPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxwyL-1eZJJSLoiyv-1oTYQQA_b5KJUhc',
    appId: '1:556603482761:android:4c1a324b5dee4d01875c58',
    messagingSenderId: '556603482761',
    projectId: 'ambulance-a27af',
    storageBucket: 'ambulance-a27af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ey3ylDZ-5XG4HA-AijFXhb8Yp3gxAIQ',
    appId: '1:556603482761:ios:720d6c22fef77381875c58',
    messagingSenderId: '556603482761',
    projectId: 'ambulance-a27af',
    storageBucket: 'ambulance-a27af.appspot.com',
    iosClientId:
        '556603482761-asqpda75q92oq448r26hit27kv0mfli6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ambulance',
  );
}
